# Prettier Configuration file
# https://prettier.io/docs/en/options.html

printWidth: 120
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
trailingComma: 'es5'
bracketSpacing: true
arrowParens: always
endOfLine: lf
