version: "3"

services:
  db:
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
    volumes:
      - dbvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  dbvol:
